/* Populate database with sample data. */

INSERT INTO animals (NAME, DATE_OF_BIRTH, WEIGHT_KG, NEUTERED, ESCAPE_ATTEMPTS) VALUES ('Agumon', '2020-02-03', 10.23, true, 0);
INSERT INTO animals (NAME, DATE_OF_BIRTH, WEIGHT_KG, NEUTERED, ESCAPE_ATTEMPTS) VALUES ('Gabumon', '2018-11-15', 8, true, 2);
INSERT INTO animals (NAME, DATE_OF_BIRTH, WEIGHT_KG, NEUTERED, ESCAPE_ATTEMPTS) VALUES ('Pikachu', '2021-01-07', 15.04, false, 1);
INSERT INTO animals (NAME, DATE_OF_BIRTH, WEIGHT_KG, NEUTERED, ESCAPE_ATTEMPTS) VALUES ('Devimon', '2017-05-12', 11, true, 5);
